spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true






